### ISSUE TITLE
Z-Score Group_By

### ISSUE THREAD

**Issue by csrvermaak** [HennieBez/Amended-R-Mini-Project#2]
Hi Hennie - ek sien nie die group_by in die JAN Z-Score calc nie:

```
zscore_eqs <- mutate(eqs_frame, z_score = (BookYield - (mean(eqs_frame$BookYield, na.rm = TRUE))/sd(eqs_frame$BookYield, na.rm = TRUE)))
```

Jy hoef ook nie `eqs_frame$` te gebruik nie

**Comment by HennieBez** [comment]
Thanks Rad,

Ek het die bogenoemde verander en aangepas,

Ek het in die proses agtergekom dat ek dieselfde fout maak indien ek die _Market Cap_ portefeulje se "**weights**" bereken

Ek het n nuwe _issue_ _geraise_ om daaraan aandag te gee

Groete,

Hennie
