### ISSUE TITLE
Market Cap Weights to be amended 

### ISSUE THREAD

**Issue by HennieBez** [HennieBez/Amended-R-Mini-Project#3]
In order to calculate cap-weighted portfolio, I'll need to use the same group-by function to correctly capture instrument level weights for the period.

Currently, my code is using the entire sample (duplicating ticker to use a a denominator to calculate the weights)

**Comment by csrvermaak** [comment]
:+1:

**Comment by HennieBez** [comment]
Updated - I believe the code is now more in line with expectations

:)
