### ISSUE TITLE
I need to figure out how to get my results in a Tibble

### ISSUE THREAD

**Issue by HennieBez** [HennieBez/Amended-R-Mini-Project#4]
This might not make sense, but currently my code reveal the results using the `summarize` function

This is good for knowing what the EY for the cap-weighted portfolio is for every month, but poses the following problem:

In order to plot a _time series_ of earnings yield for the period, I need to construct a _Tibble_ to uses as data for `ggplot` to be able to visually analyse the results.

**Comment by HennieBez** [comment]
Instead of creating a dataframe or a Tibble which only contains the EY as a column and the Date as rows (i.e. 2X3 Tibble), I have used the `mutate` and `group_by` function to ad an additional column to my existing dataframe.

`timeseries_ey <- earnings_capweighted %>%
  group_by(date) %>%
  mutate(portfolio_ey = sum(ey_weights, na.rm = TRUE)) %>%
  ungroup()`

This creates a scenario where every row in the data frame contains an observations which represents the _portfolio level earnings yield _ to correspond to the applicable month.

I am happy to discuss this and receive feedback :)

**Comment by HennieBez** [comment]
Hi @csrvermaak 

I am quite happy with the end result of this _issue_.

**Comment by csrvermaak** [comment]
@HennieBez - great stuff. You can also mention me in a pull request (which you don't have, as you're working in the master repository)
