### ISSUE TITLE
Let us start with working in R and BBG

### ISSUE THREAD

**Issue by HennieBez** [HennieBez/Amended-R-Mini-Project#7]
•	Install RStudio on a Bloomberg machine
•	Install RblpApi package
•	Download historical prices for SPX from 2003 to today and graph using ggplot (tip: bdh)
•	Set up an EQS screen (EQS<GO>) on BBG on the S&P 500 of the ROE en P/B ratio
•	Download the EQS screen for 31Dec2006 and 31Dec2007(tip: beqs)

**Comment by HennieBez** [comment]
Made great progress!

Awesome API tool :)

Perhaps we can discuss whether or not it will be possible to pull in an EQS screen which I setup as a time series @csrvermaak  ?

Current code: `eqs_dec06 <- beqs(screenName = "R Studio Assignment", date = ymd(20061231))' for December 2006.

Will it be possible to pull in these for the entire year as a dataframe ?

I look forward to the discussion

**Comment by csrvermaak** [comment]
@HennieBez , no, you can only pull one date at a time using beqs(), but you can easily loop through all the dates in the year, and row_bind()... :)

**Comment by HennieBez** [comment]
Thanks Rad !!
